### PR TITLE
Drop .idea from .gitignore

### PR DESCRIPTION
**Pull request by simPod**
.idea is not project specific, there's a better solution https://help.github.com/en/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

### CODE REVIEW

**Comment by BenMorel** [comment]
Hi, do you know how to make this solution work for TortoiseGit on Windows?

**Comment by simPod** [comment]
It doesn't respect `core.excludesfile`?

**Comment by BenMorel** [comment]
I have no idea how to configure this! 

You’re right, I’d better configure a global .gitignore, I just don’t know how to do this with TortoiseGit.

**Comment by simPod** [comment]
Do you have global gitignore at `git config --global core.excludesfile` and TortoiseGit ignores it? If so I'll create FR for them

**Pull request closed without merging**
